services:
  database:
    image: postgres:alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  backend:
    image: oven/bun
    restart: always
    working_dir: /app/backend
    environment:
      DATABASE_URL: postgres://postgres:postgres@database:5432/postgres
    volumes:
      - .:/app
    ports:
      - "3001:3000"
    command: ["sh", "-c", "bun install && bun run ./src/index.ts"]
    depends_on:
      - database

  frontend:
    image: oven/bun
    restart: always
    working_dir: /app/frontend
    environment:
      API_URL: http://backend:3000
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: ["sh", "-c", "bun install && bun run ./src/index.ts"]